# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'main-app-mp'

target 'MusicPlayer' do
  project 'Essentials/MusicPlayer.project'
  use_frameworks!
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.0'

end

target 'Services' do
  project 'Services/Services/Services.project'
  use_frameworks!

  pod 'Alamofire'

end

target 'AppNavigation' do
  project 'AppNavigation/AppNavigation/AppNavigation.project'
  use_frameworks!
end

target 'Home' do
  project 'Features/Home/Home.project'
  use_frameworks!

  pod 'SDWebImage', '~> 5.0'

  target 'HomeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire'
  end
end

target 'LaunchScreen' do
  project 'Features/LaunchScreen/LaunchScreen.project'
  use_frameworks!
end

target 'Common' do
  project 'Common/Common/Common.project'
  use_frameworks!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOX'] = 'NO'
    end
  end
end
